version: '3.9'

services:
  portofoliodb:
    image: "postgres"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
    volumes:
      - portofolio-volume:/var/lib/postgresql/data

volumes:
  portofolio-volume:
